### ISSUE TITLE
[Question] Ignore files in Visual Studio Code?

### ISSUE THREAD

**Issue by roman-petrov** [wrike/dart-code-metrics#213]
Is there any way to ignore files in Visual Studio Code? 

`ignore-files` option takes no effect in my project / environment. Should this option affect warnings displayed in Visual Studio Code, or it works only from command line analysis?..

**Comment by incendial** [comment]
@roman-petrov Hi, `ignore-files` flag is for CLI only, if you want to exclude files for analysis in an IDE, you can use setup `exclude` or `metrics-exclude` in a `analysis_options.yaml`, like:

```yaml
analyzer:
  exclude:
    - example/**
    - test/resources/**
    - test/**/examples/**

dart_code_metrics:
  metrics-exclude:
    - test/**
```
